[workspace]
resolver = "2"
exclude = ["vendor/shadowsocks"]
members = ["crates/node-core", "crates/node-panel", "crates/node-kernel", "crates/node-native", "crates/node-vision", "crates/node-reality", "crates/node-runtime"]

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "unwind"

[profile.diagnostic]
inherits = "release"
strip = "none"
debug = "line-tables-only"

[patch.crates-io]
shadowsocks = { path = "vendor/shadowsocks" }
