[package]
name = "node-native"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
async-trait = "0.1"
libc = "0.2"
node-session = { path = "../node-session" }
node-quic = { path = "../node-quic" }
node-extended = { path = "../node-extended" }
node-outbound = { path = "../node-outbound" }
bytes = "1"
futures = "0.3"
shadowsocks = { version = "=1.24.0", default-features = false, features = ["aead-cipher", "aead-cipher-2022", "aead-cipher-extra", "aead-cipher-2022-extra", "stream-cipher"] }
aes = "0.8"
blake3 = "1"
node-reality = { path = "../node-reality" }
node-vision = { path = "../node-vision" }
node-core = { path = "../node-core" }
arc-swap = "1.9.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "2"
tokio = { version = "1", features = ["rt", "macros", "net", "io-util", "sync", "time", "signal", "process"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
rustls = { version = "0.23", default-features = false, features = ["std", "ring", "tls12"] }
hickory-resolver = { version = "0.26.3", default-features = false, features = ["tokio", "tls-ring", "https-ring", "quic-ring"] }

[dev-dependencies]
rcgen = { version = "0.14", default-features = false, features = ["ring", "crypto"] }
quinn = { version = "0.11", default-features = false, features = ["runtime-tokio", "rustls-ring"] }
tokio = { version = "1", features = ["test-util"] }
